### ISSUE TITLE
Suggestion: check file path prior to processing

### ISSUE THREAD

**Issue by cherdt** [sophos/PS.Machine_Health#1]
Suggestion: check the file path and produce an error before running a series of lengthy API calls.

Steps to reproduce:

* Add a non-existent path to `Sophos_Central_Health.config`
* Run `python Sophos_Central_Health.py`

An error similar to the following is produced, but only after gathering all the data:

```
Traceback (most recent call last):
  File "Sophos_Central_Health.py", line 672, in <module>
    print_report()
  File "Sophos_Central_Health.py", line 630, in print_report
    with open(full_report_path, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/bad/path/sophos_report_21012022_16-29-09.csv'
```

**Comment by sophosukps** [comment]
That is a good call. I will do that when I get a chance. I have always trusted the user to copy and paste correctly :), but you are right it should check.

**Comment by BNWEIN** [comment]
Rather than just check, why not make it create the folder if it does not exist?

**Comment by psmichaelcurtis** [comment]
I know it is 2 years and half years since this request and I will get to it, but haven't had the time yet.
